// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShelterApi.Models;

#nullable disable

namespace ShelterApi.Migrations
{
    [DbContext(typeof(ShelterApiContext))]
    [Migration("20230423120232_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 16,
                            Name = "Taki",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = 53
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 43,
                            Name = "Ginger",
                            Sex = "Female",
                            Species = "Dog",
                            Weight = 70
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 36,
                            Name = "Rollie",
                            Sex = "Male",
                            Species = "Rabbit",
                            Weight = 6
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 26,
                            Name = "Gunther",
                            Sex = "Male",
                            Species = "Dog",
                            Weight = 74
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 60,
                            Name = "Raina",
                            Sex = "Female",
                            Species = "Cat",
                            Weight = 7
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 9,
                            Name = "Butterscotch",
                            Sex = "Male",
                            Species = "Cat",
                            Weight = 11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
